# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDFhoCzm1twmxLT8PG07UlntktxVIlQx
"""

scores = input()
scoreList = list(map(int, scores.split()))
failCount = 0
for score in scoreList:
    if score < 60:
        failCount += 1
print(failCount)